---
site:
  title: "YAML Essentials for Ansible"
  url: https://github.com/rhpds/zt-yaml-essentials-ansible
  start_page: modules::module-01.adoc

asciidoc:
  attributes:
    lab_name: "YAML Essentials for Ansible"
    release-version: master
    page-pagination: true
    duration: "40 minutes"
    audience: "Developers, SREs, Platform Engineers"

content:
  sources:
    - url: ./
      start_path: content
ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
