---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "YAML Fundamentals"
      solveButton: true
    - name: module-02
      label: "Your First Playbook"
      solveButton: true
    - name: module-03
      label: "Variables & Best Practices"
      solveButton: true
    - name: module-04
      label: "Debugging YAML"
      solveButton: true

tabs:
  - name: ">_ terminal"
    url: /wetty
  - name: "YAML Spec"
    url: https://yaml.org/spec/1.2.2/
    external: true
  - name: "Ansible Docs"
    url: https://docs.ansible.com/ansible/latest/index.html
    external: true
